public class Test {
    public static void main(String[] args) {
        FreeUser free= new FreeUser("zbanda9louch");
        PremiumUser premium = new PremiumUser("zbanda9louch_gold");
        Song s1= new Song("Memory Reboot", 145, 2023, "dance/electronic");
        Song s3=new Song("Vengeance",120,2022,"dance/electronic");
        Song s2=new Song("Ascend",146,2023,"dance/electronic");
        Song s4 = new Song("Shape of You", 234, 2017, "pop");
        Song s5 = new Song("Happy", 233, 2013, "pop");
        Song s6 = new Song("Uptown Funk", 270, 2014, "pop");
        Song s7 = new Song("Bohemian Rhapsody", 354, 1975, "rock");
        Song s8 = new Song("Hotel California", 391, 1976, "rock");
        Song s9 = new Song("Stairway to Heaven", 482, 1971, "rock");
        Artist a1=new Artist("Narvent");
        Artist a2=new Artist("Dezko");
        Artist a3=new Artist("iwilldiehere");
        Album al1= new Album("NarventAl");
        Album al2=new Album("DezkoAl");
        Album al3=new Album("iwilldiehereAl");
        al1.addSong(s1);
        al2.addSong(s2);
        al3.addSong(s3);
        al3.addSong(s9);
        al3.removeSong(s9.getTitle());
        a1.addAlbum(al1);
        a2.addAlbum(al2);
        a3.addAlbum(al3);
        Playlist p1 = new Playlist(free, "electronic");
        free.playlists.add(p1);
        free.addToPlaylist(p1, s1);
        free.addToPlaylist(p1, s2);
        free.addToPlaylist(p1, s3);
        Playlist p2=new Playlist(premium, "rock");
        premium.playlists.add(p2);
        premium.addToPlaylist(p2, s7);
        premium.addToPlaylist(p2, s8);
        premium.addToPlaylist(p2, s9);
        Playlist p3 = new Playlist(premium, "pop");
        premium.playlists.add(p3);
        premium.addToPlaylist(p3, s4);
        premium.addToPlaylist(p3, s5);
        premium.addToPlaylist(p3, s6);
        p3.showPlaylist();
        free.listen(s1);
        free.listen(s2);
        free.listen(s3);
        free.listen(s4);
        free.listen(s5);
        free.listen(s6);
        free.listen(s7);
        free.skipSong(s1);
        free.skipSong(s2);
        free.skipSong(s3);
        free.skipSong(s4);
        free.skipSong(s5);
        free.skipSong(s6);
        free.skipSong(s7);
    }
}
